import puppeteer from "puppeteer";
import { createClient } from "@supabase/supabase-js";
import config from "../config.js";

/**
 * Convert report text content to HTML for PDF generation
 * @param {string} content - The report text content
 * @param {string} title - Report title
 * @param {string} type - Report type (business-plan, pitch-deck, valuation)
 * @param {Object} idea - Idea data
 * @returns {string} HTML content
 */
export function convertReportToHTML(content, title, type, idea) {
  const reportTypeDisplay = type
    .replace("-", " ")
    .replace(/\b\w/g, (l) => l.toUpperCase());

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title} - ${reportTypeDisplay}</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 40px;
        }
        .header h1 {
            color: #2563eb;
            font-size: 28px;
            margin: 0 0 10px 0;
        }
        .header .subtitle {
            color: #666;
            font-size: 16px;
        }
        .meta-info {
            background: #f8fafc;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .meta-info h3 {
            margin-top: 0;
            color: #2563eb;
        }
        .content {
            white-space: pre-wrap;
            font-size: 14px;
        }
        .content h1, .content h2, .content h3, .content h4 {
            color: #2563eb;
            margin-top: 30px;
            margin-bottom: 15px;
            page-break-after: avoid;
        }
        .content h1 { font-size: 24px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
        .content h2 { font-size: 20px; }
        .content h3 { font-size: 18px; }
        .content h4 { font-size: 16px; }
        .content p {
            margin-bottom: 15px;
            text-align: justify;
        }
        .content ul, .content ol {
            margin-bottom: 15px;
            padding-left: 30px;
        }
        .content li {
            margin-bottom: 5px;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        @media print {
            body { margin: 0; padding: 20px; }
            .page-break { page-break-before: always; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>${title}</h1>
        <div class="subtitle">${reportTypeDisplay}</div>
    </div>

    <div class="meta-info">
        <h3>Project Information</h3>
        <p><strong>Idea:</strong> ${idea.title}</p>
        <p><strong>Category:</strong> ${idea.category}</p>
        <p><strong>Description:</strong> ${idea.description}</p>
        ${idea.tags && idea.tags.length > 0 ? `<p><strong>Tags:</strong> ${idea.tags.join(", ")}</p>` : ""}
        <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
    </div>

    <div class="content">
        ${content.replace(/\n/g, "<br>")}
    </div>

    <div class="footer">
        <p>Generated by Accelerator AI - ${new Date().getFullYear()}</p>
    </div>
</body>
</html>`;
}

/**
 * Generate PDF from HTML content and upload to Supabase Storage
 * @param {string} htmlContent - HTML content to convert to PDF
 * @param {string} fileName - Name for the PDF file
 * @param {string} bucket - Storage bucket name
 * @returns {Promise<{success: boolean, publicUrl?: string, error?: any}>}
 */
export async function generateAndUploadPDF(
  htmlContent,
  fileName,
  bucket = "reports",
) {
  let browser;

  try {
    // Launch browser
    browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const page = await browser.newPage();

    // Set content
    await page.setContent(htmlContent, { waitUntil: "networkidle0" });

    // Generate PDF buffer
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "1in",
        right: "1in",
        bottom: "1in",
        left: "1in",
      },
    });

    // Close browser
    await browser.close();
    browser = null;

    // Upload to Supabase Storage
    const supabase = createClient(
      config.supabase.url,
      config.supabase.serviceKey,
    );

    const filePath = `reports/${Date.now()}-${fileName}.pdf`;

    const { data: uploadData, error: uploadError } = await supabase.storage
      .from(bucket)
      .upload(filePath, pdfBuffer, {
        contentType: "application/pdf",
        upsert: false,
      });

    if (uploadError) {
      console.error("Error uploading PDF:", uploadError);
      return {
        success: false,
        error: uploadError,
      };
    }

    // Get public URL
    const {
      data: { publicUrl },
    } = supabase.storage.from(bucket).getPublicUrl(filePath);

    return {
      success: true,
      publicUrl,
    };
  } catch (error) {
    console.error("Error generating/uploading PDF:", error);
    if (browser) {
      await browser.close();
    }
    return {
      success: false,
      error,
    };
  }
}

/**
 * Upload a file buffer to Supabase Storage
 * @param {Buffer} fileBuffer - File buffer
 * @param {string} fileName - Original file name
 * @param {string} mimeType - MIME type
 * @param {string} bucket - Storage bucket name
 * @param {string} folder - Folder within bucket
 * @returns {Promise<{success: boolean, publicUrl?: string, filePath?: string, error?: any}>}
 */
export async function uploadFileToStorage(
  fileBuffer,
  fileName,
  mimeType,
  bucket = "reports",
  folder = "documents",
) {
  try {
    const supabase = createClient(
      config.supabase.url,
      config.supabase.serviceKey,
    );

    const timestamp = Date.now();
    const sanitizedFileName = fileName.replace(/[^a-zA-Z0-9.-]/g, "_");
    const filePath = `${folder}/${timestamp}-${sanitizedFileName}`;

    const { data: uploadData, error: uploadError } = await supabase.storage
      .from(bucket)
      .upload(filePath, fileBuffer, {
        contentType: mimeType,
        upsert: false,
      });

    if (uploadError) {
      console.error("Error uploading file:", uploadError);
      return {
        success: false,
        error: uploadError,
      };
    }

    // Get public URL
    const {
      data: { publicUrl },
    } = supabase.storage.from(bucket).getPublicUrl(filePath);

    return {
      success: true,
      publicUrl,
      filePath,
    };
  } catch (error) {
    console.error("Error uploading file to storage:", error);
    return {
      success: false,
      error,
    };
  }
}

/**
 * Delete a file from Supabase Storage
 * @param {string} filePath - Path of the file to delete
 * @param {string} bucket - Storage bucket name
 * @returns {Promise<{success: boolean, error?: any}>}
 */
export async function deleteFileFromStorage(filePath, bucket = "reports") {
  try {
    const supabase = createClient(
      config.supabase.url,
      config.supabase.serviceKey,
    );

    const { error } = await supabase.storage.from(bucket).remove([filePath]);

    if (error) {
      console.error("Error deleting file:", error);
      return {
        success: false,
        error,
      };
    }

    return {
      success: true,
    };
  } catch (error) {
    console.error("Error deleting file from storage:", error);
    return {
      success: false,
      error,
    };
  }
}
