-- Accelerator Application Schema SQL
-- Generated based on PRD.md (Product Requirements Document)
-- This file has been segregated into separate files for better organization:
-- - tables.sql: All table definitions, extensions, indexes, and storage setup
-- - rls.sql: All Row Level Security policies
-- - functions.sql: All database functions and triggers
--
-- To deploy the schema, run the files in the following order:
-- 1. tables.sql
-- 2. rls.sql
-- 3. functions.sql
--
-- Reference for future schema updates and migrations