import { createSignal, createEffect, onMount, useContext } from "solid-js";
import { LangContext } from "../../context/LangContext";
import { translations } from "../../assets/translations/translations-index.js";

const TermsOfService = () => {
  const { lang } = useContext(LangContext);
  const [currentLang, setCurrentLang] = createSignal(lang());
  const t = () => translations[currentLang()];

  createEffect(() => {
    setCurrentLang(lang());
  });

  return (
    <div class={`max-w-4xl mx-auto space-y-8  py-8 ${currentLang() === 'ar' ? 'rtl' : 'ltr'}`}>
      <div class="text-center">
        <h1 class="text-4xl font-bold text-base-content mb-4">{t().termsService}</h1>
        <p class="text-lg text-base-content/70">
          Last updated: January 2026
        </p>
      </div>

      <div class="prose prose-lg max-w-none">
        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using the iGate Startup Accelerator ("the Service"),
            you accept and agree to be bound by the terms and provision of this agreement.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            The Service is an AI-powered tool that helps entrepreneurs develop business
            plans, validate ideas, and accelerate startup development through structured
            guidance and automated analysis.
          </p>
        </section>

        <section>
          <h2>3. User Accounts</h2>
          <p>
            To use certain features, you may need to create an account. You are responsible
            for maintaining the confidentiality of your account credentials and for all
            activities that occur under your account.
          </p>
        </section>

        <section>
          <h2>4. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>Violate any laws or regulations</li>
            <li>Infringe on intellectual property rights</li>
            <li>Generate harmful, offensive, or illegal content</li>
            <li>Attempt to reverse engineer or compromise the service</li>
          </ul>
        </section>

        <section>
          <h2>5. Intellectual Property</h2>
          <p>
            The Service and its original content, features, and functionality are owned
            by iGate and are protected by international copyright, trademark, patent,
            trade secret, and other intellectual property laws.
          </p>
        </section>

        <section>
          <h2>6. AI-Generated Content</h2>
          <p>
            Content generated by AI tools within the Service is provided for informational
            purposes only. Users are responsible for verifying and validating any
            business advice or plans generated through the Service.
          </p>
        </section>

        <section>
          <h2>7. Limitation of Liability</h2>
          <p>
            The Service is provided "as is" without warranties of any kind. iGate shall
            not be liable for any indirect, incidental, special, or consequential damages
            arising out of or in connection with the use of the Service.
          </p>
        </section>

        <section>
          <h2>8. Termination</h2>
          <p>
            We may terminate or suspend your account and access to the Service at our
            discretion, without prior notice, for conduct that violates these terms.
          </p>
        </section>

        <section>
          <h2>9. Governing Law</h2>
          <p>
            These terms shall be governed by and construed in accordance with the laws
            of [Jurisdiction], without regard to conflict of law provisions.
          </p>
        </section>

        <section>
          <h2>10. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of
            the Service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2>11. Contact Information</h2>
          <p>
            For questions about these terms, please contact us at legal@igate-tech.com.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsOfService;